### ISSUE TITLE
Docker install problem

### ISSUE THREAD

**Issue by seamang** [webrecorder/webrecorder#450]
I'm having trouble with the Docker install. All appears to go OK, but accessing localhost:8089 gives me a 500 error. If I look through the docker logs the only container showing any errors is webrecorder_app, which has:

`Traceback (most recent call last):
  File "./webrecorder/main.py", line 4, in <module>
    from webrecorder.appcontroller import AppController
  File "./webrecorder/appcontroller.py", line 17, in <module>
    from pywb.rewrite.templateview import JinjaEnv
ImportError: No module named 'pywb.rewrite.templateview'
unable to load app 0 (mountpoint='') (callable not found or import error)`

docker-compose doesn't seem to have had any problem with pywb, eg:

`Building app
Step 1 : FROM webrecorder/pywb
 ---> 0ac4e6bb4d3a
`
so I don't see why this would be, and I don't have the experience with Docker to know how to debug further. 

This is on CentOS 7, which defaults to python 2.7; I have installed python 3.5.4 and symlinked /usr/bin/python to python3.5 (ditto with pip). There is a version of pywb installed with pip for python3.5.  I'm running the docker commands with sudo as it seems to be the only way it will work.

**Comment by ikreymer** [comment]
Hm, it's possible that you may have an older `webrecorder/pywb` image.. We're working to make the versions more stable with next pywb release.. For now, can you try pulling the latest webrecorder/pywb image with:

`docker pull webrecorder/pywb` and then rerunning `docker-compose build; docker-compose up -d`

**Comment by leonirlopes** [comment]
I have the same problem

**Internal Server Error**

```
# docker version
Client:
 Version:	17.12.0-ce
 API version:	1.30 (downgraded from 1.35)
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.06.2-ce
  API version:	1.30 (minimum version 1.12)
  Go version:	go1.8.3
  Git commit:	a04f55b
  Built:	Thu Sep 21 20:36:57 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

```
# cat /proc/version
Linux version 4.13.0-26-generic (buildd@lgw01-amd64-031) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)) #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

```
# python -V
Python 2.7.12
```

**Comment by muramasatheninja** [comment]
Having the same issue.

Here are the docker logs for the container that seem relevant.
`Python version: 3.5.3 (default, Jul 24 2017, 19:52:53)  [GCC 4.9.2]
Python main interpreter initialized at 0x20d3570
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 317025104 bytes (309594 KB) for 4000 cores
*** Operational MODE: preforking+async ***
No Archives Loaded
Traceback (most recent call last):
  File "./webrecorder/main.py", line 9, in <module>
    application = AppController().app
  File "./webrecorder/appcontroller.py", line 127, in __init__
    proxy_options=self._get_proxy_options())
  File "/usr/local/lib/python3.5/site-packages/wsgiprox/wsgiprox.py", line 357, in __init__
    cert_not_before=-3600)
  File "/usr/local/lib/python3.5/site-packages/certauth/certauth.py", line 73, in __init__
    res = self.load_root_ca_cert(overwrite=overwrite)
  File "/usr/local/lib/python3.5/site-packages/certauth/certauth.py", line 95, in load_root_ca_cert
    self.ca_file_cache[ROOT_CA] = cert_str
  File "/usr/local/lib/python3.5/site-packages/certauth/certauth.py", line 276, in __setitem__
    with open(filename, 'wb') as fh:
PermissionError: [Errno 13] Permission denied: './proxy-certs/webrecorder-ca.pem'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
`
I tried replacing the webrecorder-ca.pem with a sample file since I didn't have time to generate one but it still errors out.
