### ISSUE TITLE
offline support (public suffix list fetching)

### ISSUE THREAD

**Issue by kzahel** [webrecorder/webrecorder#601]
I'm running an airgapped webrecorder and notice that it doesn't like to start up, I follow the logs for the webrecorder_app_1 container and see some errors:

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='publicsuffix.org', port=443): Max retries exceeded with url: /list/public_suffix_list.dat (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd87b8fce48>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /publicsuffix/list/master/public_suffix_list.dat (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd87b8b98d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

What I have to do for now is put it on the network, let it start up, and then take it back offline. It would be really cool to be able to cache this file on disk somewhere, perhaps.

Webrecorder is otherwise working really, really great for us!

**Comment by kzahel** [comment]
Just for clarification, it "starts up" just fine, and actually the app loads OK. I can browse the home page, go to a public collection. It's only when going to an actual recording playback URL that the app "hangs" and doesn't begin playback.
