### ISSUE TITLE
Unable to authenticate with SMTP server

### ISSUE THREAD

**Issue by Serkan-devel** [webrecorder/webrecorder#628]
I've tried setting up an account locally, entering my mail address, username and password (Not Real Name, which was optional), did some debugging and found this error message right after hitting "Register"

<pre>
app_1         | [pid: 11|app: 0|req: 6/14] 172.20.0.1 () {48 vars in 806 bytes} [Mon Oct 15 17:14:02 2018] GET /api/v1/auth/check_username/serkan => generated 17 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3 switches on core 399)
recorder_1    | Temp Dir Check
app_1         | [pid: 11|app: 0|req: 7/15] 172.20.0.1 () {52 vars in 865 bytes} [Mon Oct 15 17:14:40 2018] POST /api/v1/auth/register => generated 122 bytes in 29 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 399)
nginx_1       | 172.20.0.1 - - [15/Oct/2018:17:14:40 +0000] "POST /api/v1/auth/register HTTP/1.1" 200 122 "http://localhost:8089/_register" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0; Waterfox) Gecko/20100101 Firefox/56.2.3"
app_1         | 2018-10-15 17:14:41: [ERROR]: Error sending email: (535, b'5.7.8 Error: authentication failed: authentication failure')
app_1         | Traceback (most recent call last):
app_1         |   File "/usr/local/lib/python3.5/site-packages/cork/cork.py", line 970, in _send
app_1         |     session.login(self._conf['user'], self._conf['pass'])
app_1         |   File "/usr/local/lib/python3.5/smtplib.py", line 729, in login
app_1         |     raise last_exception
app_1         |   File "/usr/local/lib/python3.5/smtplib.py", line 720, in login
app_1         |     initial_response_ok=initial_response_ok)
app_1         |   File "/usr/local/lib/python3.5/smtplib.py", line 641, in auth
app_1         |     raise SMTPAuthenticationError(code, resp)
app_1         | smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: authentication failure')
</pre>

how do I configure email locally for this?

**Comment by ikreymer** [comment]
Apologies for delay in response, we are working on making the local deploy process easier.

You can set the SMTP server to the default internal SMTP which is:

```
EMAIL_SMTP_URL=smtp://test@localhost:archive@webrecorder_mailserver_1:25
```

This should already be the default configuration. Unfortunately, some mail servers may not accept mail from this server (or flag it as spam).

We are working on a way to register users w/o having to send email if the SMTP server is not set.

Additionally, you can also create a user directly through the command line on your own instance by running:

`docker exec -it webrecorder_app_1 python -m webrecorder.admin -c` and follow the command line instructions.

**Comment by ikreymer** [comment]
It should be set in the `wr.env` which is auto-generated from wr_sample.env. It should be in the root of the webrecorder directory. This is also the default setting, it wasn't clear if you've made changes to it, but that setting should work with the default SMTP server running in the `mailserver` container.

**Comment by Serkan-devel** [comment]
Well, I didn't manage to do it with setting up SMTP but the docker command posted, worked for me.

I don't know if I should close this issue because it's resolved for my situation, but others might still have issues with email still
