### ISSUE TITLE
ReferenceError: window is not defined & asset not found errors

### ISSUE THREAD

**Issue by Nold360** [webrecorder/webrecorder#645]
I was trying to run webrecorder on my docker-host. All i did was following the four steps under "Running Locally", but all i get is the "maintenance-site" of webrecorder.

Here are some logs from the nginx & frontend container:
```
nginx_1       | 2018/11/02 08:31:02 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.160, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.9:8095/", host: "hive.lan:8089"
nginx_1       | 192.168.1.160 - - [02/Nov/2018:08:31:02 +0000] "GET / HTTP/1.1" 502 9603 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
nginx_1       | 2018/11/02 08:31:03 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.160, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.9:8095/", host: "hive.lan:8089"
nginx_1       | 192.168.1.160 - - [02/Nov/2018:08:31:03 +0000] "GET / HTTP/1.1" 502 9603 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
nginx_1       | 2018/11/02 08:31:03 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.160, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.9:8095/", host: "hive.lan:8089"
nginx_1       | 192.168.1.160 - - [02/Nov/2018:08:31:03 +0000] "GET / HTTP/1.1" 502 9603 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
nginx_1       | 2018/11/02 08:31:03 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.160, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.9:8095/", host: "hive.lan:8089"
nginx_1       | 192.168.1.160 - - [02/Nov/2018:08:31:03 +0000] "GET / HTTP/1.1" 502 9603 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
```

```
frontend_1    | [0] 08:31:29 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/Button.css
frontend_1    | [0] 08:31:29 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/Button.css
frontend_1    | [0] 08:31:29 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/ButtonWrap.css
frontend_1    | [0] 08:31:29 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/IconButton.css
frontend_1    | [0] 08:31:29 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/ButtonWrap.css
frontend_1    | [0] 08:31:29 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/IconButton.css
frontend_1    | [0] 08:31:29 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/ButtonGroup.css
frontend_1    | [0] 08:31:29 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/InputPopover.css
frontend_1    | [0] 08:31:30 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/Dropdown.css
frontend_1    | [0] 08:31:30 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/ButtonGroup.css
frontend_1    | [0] 08:31:30 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/InputPopover.css
frontend_1    | [0] 08:31:30 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/lib/EditorToolbar.css
frontend_1    | [0] 08:31:30 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/Dropdown.css
frontend_1    | [0] 08:31:31 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/lib/EditorToolbar.css
frontend_1    | [0] 08:31:31 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/ImageSpan.css
frontend_1    | [0] 08:31:32 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/ui/ImageSpan.css
frontend_1    | [0] 08:31:32 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/Draft.global.css
frontend_1    | [0] 08:31:32 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/RichTextEditor.css
frontend_1    | [0] 08:31:32 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/Draft.global.css
frontend_1    | [0] 08:31:32 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-rte/lib/RichTextEditor.css
frontend_1    | [0] 08:31:47 1|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-virtualized/styles.css
frontend_1    | [0] 08:31:47 0|frontend  | [webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-virtualized/styles.css
recorder_1    | Temp Dir Check
frontend_1    | [0] 08:32:02 1|frontend  | ReferenceError: window is not defined
frontend_1    | 08:32:02 1|frontend  |     at Object.<anonymous> (/code/src/components/player/Webview/index.js:15:25)
frontend_1    | [0] 08:32:02 1|frontend  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
frontend_1    | [0] 08:32:02 1|frontend  |     at loader (/code/node_modules/babel-register/lib/node.js:144:5)
frontend_1    | [0] 08:32:02 1|frontend  |     at Object.require.extensions.(anonymous function) [as .js] (/code/node_modules/babel-register/lib/node.js:154:7)
frontend_1    | [0] 08:32:02 1|frontend  |     at Module.load (internal/modules/cjs/loader.js:599:32)
frontend_1    | [0] 08:32:02 1|frontend  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
frontend_1    | [0] 08:32:02 1|frontend  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
frontend_1    | [0] 08:32:02 1|frontend  |     at Module.require (internal/modules/cjs/loader.js:637:17)
frontend_1    | 08:32:02 1|frontend  |     at require (internal/modules/cjs/helpers.js:20:18)
frontend_1    | [0] 08:32:02 1|frontend  |     at Object.<anonymous> (/code/src/containers/Replay/Replay.js:23:1)
frontend_1    | [0] 08:32:02 0|frontend  | ReferenceError: window is not defined
frontend_1    | [0] 08:32:02 0|frontend  |     at Object.<anonymous> (/code/src/components/player/Webview/index.js:15:25)
frontend_1    | [0] 08:32:02 0|frontend  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
frontend_1    | [0] 08:32:02 0|frontend  |     at loader (/code/node_modules/babel-register/lib/node.js:144:5)
frontend_1    | [0] 08:32:02 0|frontend  |     at Object.require.extensions.(anonymous function) [as .js] (/code/node_modules/babel-register/lib/node.js:154:7)
frontend_1    | [0] 08:32:02 0|frontend  |     at Module.load (internal/modules/cjs/loader.js:599:32)
frontend_1    | [0] 08:32:02 0|frontend  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
frontend_1    | [0] 08:32:02 0|frontend  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
frontend_1    | [0] 08:32:02 0|frontend  |     at Module.require (internal/modules/cjs/loader.js:637:17)
frontend_1    | [0] 08:32:02 0|frontend  |     at require (internal/modules/cjs/helpers.js:20:18)
frontend_1    | [0] 08:32:02 0|frontend  |     at Object.<anonymous> (/code/src/containers/Replay/Replay.js:23:1)
```

**Comment by m4rk3r** [comment]
Hi @Nold360, that's a non-breaking issue on the server build and shouldn't prevent it from completing. The build can take 30s to a minute, have you try refreshing since?

**Comment by Nold360** [comment]
Yea, i waited several minutes. Now i've tried running it on my notebook. Same issue.

I connected to the frontend container & installed netstat. It seems like there is no service listening to port 8095 even though some processes are running:
```
root@d5034c3bb7d6:/code# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 07:39 ?        00:00:00 sh run.sh
root        37     1  0 07:39 ?        00:00:00 npm                                    
root        47    37  0 07:39 ?        00:00:00 sh -c concurrently --kill-others "npm run start-docker-pr
root        48    47  0 07:39 ?        00:00:00 node /code/node_modules/.bin/concurrently --kill-others n
root        54    48  0 07:39 ?        00:00:00 /bin/sh -c npm run start-docker-prod
root        55    54  0 07:39 ?        00:00:00 npm                                          
root        65    55  0 07:39 ?        00:00:00 sh -c better-npm-run start-docker-prod
root        66    65  0 07:39 ?        00:00:00 node /code/node_modules/.bin/better-npm-run start-docker-
root        72    66  0 07:39 ?        00:00:00 sh -c pm2 start ./bin/server.js -i 0 --no-daemon --name '
root        73    72  0 07:39 ?        00:00:01 node /code/node_modules/.bin/pm2 start ./bin/server.js -i
root        83    73  6 07:39 ?        00:00:24 node /code/bin/server.js                                 
root        89    73  6 07:39 ?        00:00:25 node /code/bin/server.js                                 
root        99    73  6 07:39 ?        00:00:24 node /code/bin/server.js                                 
root       109    73  6 07:39 ?        00:00:24 node /code/bin/server.js                                 
root       115    73  7 07:39 ?        00:00:26 node /code/bin/server.js                                 
root       129    73  7 07:39 ?        00:00:25 node /code/bin/server.js                                 
root       135    73  7 07:39 ?        00:00:26 node /code/bin/server.js                                 
root       149    73  7 07:39 ?        00:00:26 node /code/bin/server.js                                 
root       177     0  0 07:41 pts/0    00:00:00 bash
root       241   177  0 07:45 pts/0    00:00:00 ps -ef
```

**Comment by m4rk3r** [comment]
Hey @Nold360 thanks for the extra info. Caught the issue, import from the player build snuck in, grabbing latest master should take care of it. Thanks again for spotting this issue!
