### ISSUE TITLE
Record WhatsApp Web Usage

### ISSUE THREAD

**Issue by arjunvenkatraman** [webrecorder/webrecorder#735]
When trying to open the WhatsApp web client at https://web.whatsapp.com -
![image](https://user-images.githubusercontent.com/743783/62819620-4b46a700-bb75-11e9-8aec-502a574f8a29.png)

In the console - 

```js
The Components object is deprecated. It will soon be removed. webrecorder.io
The ‘content’ attribute of Window objects is deprecated.  Please use ‘window.top’ instead. pywb.js:19:24698
onmozfullscreenchange is deprecated. pywb.js:19:24698
onmozfullscreenerror is deprecated. pywb.js:19:24698
The script from “https://content.webrecorder.io/static_cors/bundle/autoFetchW…cp7awi%5C%5C%2Frecord%5C%5C%2F%5B%5E%2F%5D%2B%5C%5C%2F%22%7D” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. web.whatsapp.com
The Components object is deprecated. It will soon be removed. web.whatsapp.com
Firefox can’t establish a connection to the server at wss://content.webrecorder.io/temp-YQISX7GF/temp/sxsnk7n2rvcp7awi/record/20190810081531ws_/wss://web.whatsapp.com/ws. 5 pywb.js:19:77181
Firefox can’t establish a connection to the server at wss://content.webrecorder.io/temp-YQISX7GF/temp/sxsnk7n2rvcp7awi/record/20190810081531ws_/wss://web.whatsapp.com/ws. pywb.js:19:77181
```

I wonder if the reason it's failing is because WhatsApp web already uses the WS layer to pull the QR code?

```js
wss://content.webrecorder.io/temp-YQISX7GF/temp/sxsnk7n2rvcp7awi/record/20190810081531ws_/wss://web.whatsapp.com/ws. 5 pywb.js:19:77181
```

**Comment by arjunvenkatraman** [comment]
This on an updated version of Firefox 68.0.1 x64 Ubuntu 18.04
